DROP TABLE CLIENTES IF EXISTS;
CREATE TABLE CLIENTES (
id INT NOT NULL,
name VARCHAR(100) NOT NULL,
lastname VARCHAR(100) NOT NULL,
dni INT NOT NULL);

DROP TABLE PRODUCTOS IF EXISTS;
CREATE TABLE PRODUCTOS(
    id INT NOT NULL,
    description VARCHAR(150) NOT NULL,
    code VARCHAR(50) NOT NULL,
    stock INT NOT NULL,
    price DOUBLE NOT NULL
);

DROP TABLE INVOICE IF EXISTS;
CREATE TABLE INVOICE(
    id INT NOT NULL,
    client_id INT NOT NULL,
    created_at VARCHAR(100) NOT NULL,
    total DOUBLE
);

DROP TABLE INVOICE_DETAILS IF EXISTS;
CREATE TABLE INVOICE_DETAILS(
    invoice_id INT NOT NULL,
    invoice_detail_id INT NOT NULL,
    amount INT NOT NULL,
    product_id INT NOT NULL,
    price DOUBLE NOT NULL);

DROP TABLE VENTAS IF EXISTS;
