DROP TABLE INVOICE_DETAILS IF EXISTS;
DROP TABLE INVOICE IF EXISTS;
DROP TABLE PRODUCTOS IF EXISTS;
DROP TABLE CLIENTES IF EXISTS;


CREATE TABLE CLIENTES (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
lastname VARCHAR(100) NOT NULL,
dni INT NOT NULL);


CREATE TABLE PRODUCTOS(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    description VARCHAR(150) NOT NULL,
    code VARCHAR(50) NOT NULL,
    stock INT NOT NULL,
    price DOUBLE NOT NULL
);

CREATE TABLE INVOICE(
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    client_id INT NOT NULL,
    created_at DATE DEFAULT CURRENT_DATE,
    total DOUBLE,
    FOREIGN KEY(client_id) REFERENCES CLIENTES(id)
);

CREATE TABLE INVOICE_DETAILS(
    invoice_id INT NOT NULL ,
    invoice_detail_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    amount INT NOT NULL,
    product_id INT NOT NULL,
    price DOUBLE NOT NULL,
    FOREIGN KEY(product_id) REFERENCES PRODUCTOS(id),
    FOREIGN KEY(invoice_id) REFERENCES INVOICE(id)
    );
